#!/usr/bin/env python3
"""Generate a static, reusable interactive A4 earnings dashboard."""
from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = ROOT / "earnings-dashboard"
INCOME_HIGHLIGHT_KEYS = ("revenue", "gross_profit", "operating_income", "net_income")

METADATA: dict[str, dict[str, Any]] = {
    "revenue": {"description": "Revenue recognized during the reported period.", "why_it_matters": "Shows the scale and growth of the core business.", "directionality": "Higher is generally better when growth is profitable.", "formula": "Reported revenue for the period", "scale": [{"label": "Declining", "max": 0, "signal": "negative"}, {"label": "Stable", "max": 0.10, "signal": "neutral"}, {"label": "Strong growth", "max": None, "signal": "positive"}]},
    "gross_profit": {"description": "Revenue remaining after direct costs.", "why_it_matters": "Funds operating expenses, investment, and profit.", "directionality": "Higher and expanding is generally better.", "formula": "Revenue − cost of revenue"},
    "operating_income": {"description": "Profit from core operations before interest and taxes.", "why_it_matters": "Measures operating execution and cost discipline.", "directionality": "Higher is generally better.", "formula": "Gross profit − operating expenses"},
    "net_income": {"description": "Profit attributable after all recognized expenses.", "why_it_matters": "Captures the period's bottom-line result.", "directionality": "Higher and durable is generally better.", "formula": "Revenue − all expenses, interest, and tax"},
    "eps_diluted": {"description": "Earnings allocated to each diluted weighted-average share.", "why_it_matters": "Connects company profit to shareholder economics.", "directionality": "Higher sustainable EPS is generally better.", "formula": "Net income ÷ diluted weighted-average shares"},
    "operating_cash_flow": {"description": "Cash generated by operating activities.", "why_it_matters": "Tests whether accounting earnings convert into cash.", "directionality": "Higher and consistent is generally better.", "formula": "Cash inflows from operations − operating cash outflows"},
    "capex": {"description": "Cash or obligations used for long-lived productive assets.", "why_it_matters": "Indicates reinvestment needs and pressure on free cash flow.", "directionality": "Context dependent; efficiency matters more than simply lower or higher.", "formula": "Purchases/investment in property and equipment"},
    "cash": {"description": "Cash and cash equivalents at period end.", "why_it_matters": "Supports liquidity, resilience, and strategic flexibility.", "directionality": "More liquidity helps, but excess idle cash can reduce returns.", "formula": "Reported cash and cash equivalents"},
    "total_assets": {"description": "Total recognized economic resources.", "why_it_matters": "Provides balance-sheet scale and capital-intensity context.", "directionality": "Context dependent.", "formula": "Current assets + non-current assets"},
    "total_liabilities": {"description": "Total recognized obligations.", "why_it_matters": "Frames leverage, fixed claims, and financial risk.", "directionality": "Lower relative to assets and cash flow is usually safer.", "formula": "Current liabilities + non-current liabilities"},
    "total_equity": {"description": "Residual accounting interest after liabilities.", "why_it_matters": "Shows accumulated capital and losses, though buybacks can reduce it.", "directionality": "Positive and improving is usually healthier; interpret with capital returns.", "formula": "Total assets − total liabilities"},
    "long_term_debt": {"description": "Debt due beyond the current period.", "why_it_matters": "Creates fixed claims on future cash flows.", "directionality": "Lower leverage is generally safer, subject to capital structure.", "formula": "Reported current and non-current long-term borrowings"},
    "shares_diluted": {"description": "Weighted-average shares including dilutive instruments.", "why_it_matters": "Determines per-share ownership and earnings dilution.", "directionality": "Lower is generally better when caused by value-accretive repurchases.", "formula": "Basic shares + dilutive share equivalents"},
    "operating_margin": {"description": "Share of revenue retained as operating profit.", "why_it_matters": "Measures operating efficiency and pricing power.", "directionality": "Higher and durable is generally better.", "formula": "Operating income ÷ revenue"},
    "gross_margin": {"description": "Share of revenue remaining after direct costs.", "why_it_matters": "Shows product economics and pricing/cost performance.", "directionality": "Higher and durable is generally better.", "formula": "Gross profit ÷ revenue"},
    "net_margin": {"description": "Share of revenue retained as net income.", "why_it_matters": "Summarizes bottom-line profitability.", "directionality": "Higher and durable is generally better.", "formula": "Net income ÷ revenue"},
    "pe_ttm": {"description": "Price paid for each dollar of trailing earnings.", "why_it_matters": "Frames valuation relative to realized earnings.", "directionality": "Lower can be more attractive, but quality and growth matter.", "formula": "Share price ÷ trailing-twelve-month EPS", "scale": [{"label": "Attractive", "max": 18, "signal": "positive"}, {"label": "Moderate", "max": 35, "signal": "neutral"}, {"label": "Premium", "max": 50, "signal": "caution"}, {"label": "Extreme", "max": None, "signal": "negative"}]},
    "ps_annualized": {"description": "Market capitalization relative to annualized quarterly revenue.", "why_it_matters": "Useful when earnings are immature or volatile, but does not capture margins.", "directionality": "Lower is generally better, all else equal.", "formula": "Market capitalization ÷ annualized reported-quarter revenue", "scale": [{"label": "Low / potentially attractive", "max": 2, "signal": "positive"}, {"label": "Moderate", "max": 5, "signal": "neutral"}, {"label": "High", "max": 10, "signal": "caution"}, {"label": "Extreme", "max": None, "signal": "negative"}]},
    "fcf_yield_annualized": {"description": "Annualized free cash flow relative to market value.", "why_it_matters": "Estimates cash generation available per dollar invested.", "directionality": "Higher is generally better when cash flow is sustainable.", "formula": "Annualized free cash flow ÷ market capitalization", "scale": [{"label": "Low", "max": 2.5, "signal": "caution"}, {"label": "Healthy", "max": 6, "signal": "neutral"}, {"label": "Attractive", "max": None, "signal": "positive"}]},
    "ev_ebitda": {"description": "Enterprise value relative to EBITDA.", "why_it_matters": "Compares operating valuation across different capital structures.", "directionality": "Lower is generally better, subject to growth and quality.", "formula": "Enterprise value ÷ trailing EBITDA"},
}


def _key(row: dict[str, Any]) -> str:
    return str(row.get("key") or row.get("label") or "metric").strip().lower().replace(" ", "_").replace("/", "_")


def _metric(row: dict[str, Any], source_note: str = "") -> dict[str, Any]:
    key = _key(row)
    meta = METADATA.get(key, {})
    raw = row.get("value")
    comparison = row.get("comparison") or row.get("assessment") or "Comparison unavailable"
    citation = row.get("citation")
    if isinstance(citation, list):
        citation = citation[0] if citation else {}
    if not isinstance(citation, dict):
        citation = {}
    return {
        "key": key,
        "name": row.get("label") or key.replace("_", " ").title(),
        "raw_value": raw,
        "display_value": row.get("display", "N/A" if raw is None else str(raw)),
        "comparison": comparison,
        "status": row.get("signal") or row.get("tier") or "neutral",
        "tier": row.get("tier"),
        "assessment": row.get("assessment") or comparison,
        "description": row.get("definition") or meta.get("description", "A verified company-reported financial measure."),
        "why_it_matters": row.get("impact") or meta.get("why_it_matters", "Provides context for operating performance, financial position, or valuation."),
        "directionality": row.get("directionality") or meta.get("directionality", "Interpret with the company's trend, peers, and business model."),
        "formula": row.get("formula") or meta.get("formula", "See the cited source and calculation context."),
        "scale": row.get("scale") if row.get("scale") is not None else meta.get("scale", []),
        "source_note": row.get("source_note") or source_note or citation.get("source", "Verified report data"),
        "source_date": row.get("source_date"),
    }


def _channel_signal(row: dict[str, Any]) -> dict[str, Any]:
    """Preserve explicit signals or derive one from unambiguous directional evidence."""
    if row.get("signal") or row.get("tier"):
        return row
    detail = str(row.get("detail") or row.get("desc") or "").lower()
    positive_phrases = (
        "strong pipeline", "opportunity", "expand", "growth", "high cadence",
        "full-scale production", "critical communications", "more than $", "eliminate",
    )
    negative_phrases = (
        "decrease", "decline", "lower", "loss", "negative", "delay", "setback",
    )
    positive = any(phrase in detail for phrase in positive_phrases)
    negative = any(phrase in detail for phrase in negative_phrases)
    enriched = dict(row)
    enriched["signal"] = "neutral" if positive == negative else "positive" if positive else "negative"
    return enriched


def _call_rows(data: dict[str, Any]) -> list[dict[str, Any]]:
    rows = data.get("earnings_call_summary", {}).get("insights") or data.get("transcript_insights", [])
    output: list[dict[str, Any]] = []
    for row in rows:
        enriched = dict(row)
        if str(row.get("topic") or "").strip().lower() == "management tone":
            category = row.get("confidence_category")
            subcategory = row.get("confidence_subcategory")
            detail = row.get("detail")
            if category and subcategory and detail:
                enriched["detail"] = f"{category} → {subcategory}, {detail}"
        output.append(enriched)
    return output


def build_dashboard_data(data: dict[str, Any]) -> dict[str, Any]:
    """Convert the company-neutral analysis schema to the dashboard schema."""
    valuation = data.get("valuation", {})
    valuation_rows = valuation.get("rows", [])
    if not valuation_rows:
        valuation_rows = [
            {"key": key, "label": label, "value": valuation.get(key), "display": "N/A" if valuation.get(key) is None else str(valuation[key])}
            for key, label in (("pe_ttm", "P/E (TTM)"), ("ps_annualized", "P/S (annualized)"), ("fcf_yield_annualized", "FCF Yield (annualized)"))
        ]
    sources = data.get("sources", {})
    financial_rows = data.get("financials", {}).get("rows", [])
    financial_by_key = {_key(row): row for row in financial_rows}
    income_highlights = [financial_by_key[key] for key in INCOME_HIGHLIGHT_KEYS if key in financial_by_key]
    return {
        "schema_version": 2,
        "company": {
            "ticker": data.get("ticker", "N/A"),
            "period": f"{data.get('fiscal_period', 'N/A')} FY{data.get('fiscal_year', 'N/A')}",
            "report_date": data.get("report_date"),
            "call_date": sources.get("transcript_call_date"),
            "grade": data.get("grade", {}).get("letter", "N/A"),
            "confidence": data.get("grade", {}).get("confidence"),
            "recommendation": data.get("thesis", {}).get("recommendation", "INSUFFICIENT DATA"),
            "price": valuation.get("current_price"),
            "market_cap": valuation.get("market_cap"),
            "pe_ttm": valuation.get("pe_ttm"),
            "high_52": valuation.get("high_52"),
            "low_52": valuation.get("low_52"),
            "test_run": bool(data.get("test_run")),
        },
        "sections": {
            "income_statement": [_metric(row) for row in income_highlights],
            "key_ratios": [_metric(row) for row in data.get("financials", {}).get("key_ratios", [])],
            "valuation": [_metric(row, valuation.get("quote_source", "Verified market data")) for row in valuation_rows],
            "valuation_regime": valuation.get("regime_label", "Valuation"),
            "short_interest_sbc": [_metric(row) for row in valuation.get("risk_rows", [])],
            "capital_liquidity": data.get("capital_liquidity", {}).get("items", []),
            "guidance": data.get("guidance", {}).get("rows", []),
            "earnings_call": _call_rows(data),
            "channels": [_channel_signal(row) for row in data.get("channels", {}).get("items", [])],
            "strategic_pillars": data.get("strategic_pillars", []),
            "risks": data.get("risks", []),
            "thesis": data.get("thesis", {}),
        },
        "sources": sources,
        "warnings": data.get("warnings", []),
        "grade_breakdown": data.get("grade_breakdown", {}),
    }


def create_interactive_dashboard(data: dict[str, Any], output_dir: str) -> str:
    """Create a complete static site and return its index path."""
    target = Path(output_dir)
    if target.exists():
        shutil.rmtree(target)
    shutil.copytree(TEMPLATE_DIR, target, ignore=shutil.ignore_patterns("data", "*.pyc", "__pycache__"))
    data_dir = target / "data"
    data_dir.mkdir(parents=True, exist_ok=True)
    payload = build_dashboard_data(data)
    json_text = json.dumps(payload, indent=2, ensure_ascii=False)
    ticker = str(data.get("ticker", "REPORT")).upper()
    period = f"{data.get('fiscal_year', 'NA')}-{data.get('fiscal_period', 'NA')}"
    named_json = data_dir / f"{ticker}-{period}.json"
    named_json.write_text(json_text, encoding="utf-8")
    (data_dir / "report.json").write_text(json_text, encoding="utf-8")
    (data_dir / "report.js").write_text("window.EARNINGS_REPORT = " + json_text + ";\n", encoding="utf-8")
    return str(target / "index.html")
